[INFO ] 2018-04-28 10:04:47 com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1@(DubboProtocol.java:130): [DUBBO] disconected from /192.168.186.1:20881,url:dubbo://192.168.186.1:20881/com.taotao.content.service.ContentService?anyhost=true&application=taotao-portal-web&check=false&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.taotao.content.service.ContentService&methods=getContentByCid,addContent&pid=24228&revision=0.0.1-SNAPSHOT&side=consumer&timeout=300000&timestamp=1524142188857, dubbo version: 2.5.3, current host: 192.168.186.1
     [WARN ] 2018-04-28 10:04:50 com.alibaba.dubbo.remoting.transport.AbstractClient$1@(AbstractClient.java:160): [DUBBO] client reconnect to 192.168.186.1:20881 find error . url: dubbo://192.168.186.1:20881/com.taotao.content.service.ContentService?anyhost=true&application=taotao-portal-web&check=false&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.taotao.content.service.ContentService&methods=getContentByCid,addContent&pid=24228&revision=0.0.1-SNAPSHOT&side=consumer&timeout=300000&timestamp=1524142188857, dubbo version: 2.5.3, current host: 192.168.186.1
     com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.186.1:20881/com.taotao.content.service.ContentService?anyhost=true&application=taotao-portal-web&check=false&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.taotao.content.service.ContentService&methods=getContentByCid,addContent&pid=24228&revision=0.0.1-SNAPSHOT&side=consumer&timeout=300000&timestamp=1524142188857) failed to connect to server /192.168.186.1:20881, error message is:Connection refused: no further information: /192.168.186.1:20881
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280)
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information: /192.168.186.1:20881
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	... 3 more
